---

- name: add_adafruit_key
  apt_key:
    url: https://apt.adafruit.com/apt.adafruit.com.gpg.key
    state: present

- name: add_adafruit_repo
  apt_repository:
    state: present
    repo: deb http://apt.adafruit.com/raspbian/ jessie main

- name: install_dependencies
  apt: name={{item}} state=installed
  with_items:
    - git
    - maven
    - node
    - oracle-java8-jdk

- name: select_jdk8
  alternatives:
    name: java
    path: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/bin/java

- name: checkout_signalk
  git:
    repo: https://github.com/SignalK/signalk-java.git
    dest: /opt/signalk-java

- name: copy_init_file
  copy:
    src: signalk-java
    dest: /etc/init.d/signalk-java
    mode: 755
