---

- name: checkout_kplex
  git:
    repo: https://github.com/stripydog/kplex.git
    dest: /usr/src/kplex

- name: build_and_install_kplex
  command: "{{item}}"
  args:
    chdir: /usr/src/kplex
  with_items:
    - make
    - make install

- name: copy_init_file
  copy:
    remote_src: true
    src: /usr/src/kplex/kplex.init
    dest: /etc/init.d/kplex
    mode: 755

- name: copy_kplex_config
  copy:
    src: kplex.conf
    dest: /etc/kplex.conf

- name: enable_kplex_startup
  service:
    name: kplex
    enabled: yes
    state: restarted
